version: 2.1

jobs:
  build-and-push-docker-image:
    docker: 
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t vcc-circleci-test-image:latest .
      - run:
          name: dockerhub login
          command: docker login --username videocursoscloud -p $DOCKER_PASS
      - run:
          name: Tag Image
          command: docker tag vcc-circleci-test-image:latest videocursoscloud/vcc-circleci-test-image:latest
      - run:
          name: Push image
          command: docker push videocursoscloud/vcc-circleci-test-image:latest         

workflows:
  say-hello-workflow:
    jobs:
      - build-and-push-docker-image:
          context: docker-hub-vcc
