version: 2.1

environments:
  dev: &dev_environments
       - dev 
       - uat
  staging: &test_environments
       - staging
       - testing
  prod: &prod_environments
       - prod
jobs:
  hello:
    docker: 
      - image: cimg/python:3.10.6
    steps:   
      - run: |
          echo "hello there"
  test:
    parameters:
      environment:
        type: string
    docker: 
      - image: cimg/python:3.10.6
    steps:   
      - run: |
          echo "hello there << parameters.environment >>"

workflows:
  test-dev:
    jobs:
      - test:
          matrix:
            alias: dev-environments
            parameters:
              environment: *dev_environments
  test-staging:
    jobs:
      - test:
          matrix:
            alias: test-environments
            parameters:
              environment: *test_environments
  prod-staging:
    jobs:
      - test:
          matrix:
            alias: prod-environments
            parameters:
              environment: *prod_environments
