version: 2.1

jobs:
  hello:
    docker: 
      - image: cimg/python:3.10.6
    steps:   
      - run: |
          echo "hello there"
  test:
    parameters:
      os: 
        type: string
      version:
        type: string
    docker: 
      - image: cimg/python:3.10.6
    steps:   
      - run: |
          echo "hello there << parameteres.os >> << parameters.version >>"

workflows:
  hello:
    jobs:
      - hello:
          context: docker-hub-vcc
   all-tests:
     jobs:
       - test:
           matrix:
             parameters:
             os: [docker, linux, macos]
             version: ["1","2"]
