version: 2.1

jobs:
  hello:
    docker: 
      - image: cimg/python:3.10.6
    steps:   
      - run: |
          echo "hello there"
  test:
    parameters:
      environment:
        type: string
    docker: 
      - image: cimg/python:3.10.6
    steps:   
      - run: |
          echo "hello there << parameters.environment >>"

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              environment: [ "dev", "testing", "prod"]
