version: 2.1

jobs:
  build-docker-image:
    docker: 
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t pythontest .

  say-hello:
    docker:
      - image: cimg/python:3.10.6
    steps:
      - checkout
      - run:
          name: "install requirements"
          command: "pip3 install -r requirements.txt"      
   
      - run: python --version

workflows:
  say-hello-workflow:
    jobs:
      - build-docker-image
