version: 2.1

jobs:
  build-and-push-docker-image:
    docker: 
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: docker build -t vcc-circleci-test-image:latest .
      - run:
          name: dockerhub login
          command: echo "$DOCKER_PASS" | docker login --username videocursoscloud --password-stdin
  


workflows:
  say-hello-workflow:
    jobs:
      - build-and-push-docker-image:
          context: docker-hub-vcc
