version: 2.1

jobs:
  hello:
    docker: 
      - image: cimg/python:3.10.6
    steps:   
      - run: |
          echo "hello there"

workflows:
  hello:
    jobs:
      - hello
          context: docker-hub-vcc
